"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
require("reflect-metadata");
tslib_1.__exportStar(require("./core"), exports);
tslib_1.__exportStar(require("./http"), exports);
var factory_1 = require("./factory");
exports.Factory = factory_1.default;
var egg_1 = require("egg");
exports.BaseController = egg_1.Controller;
